<a href="https://colab.research.google.com/github/sagarkakkar03/MachineLearning/blob/main/LinearRegressionExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('Salary_Data.csv')
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [11]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [12]:
df.isnull().sum()

YearsExperience    1
Salary             1
dtype: int64

In [13]:
df['YearsExperience'].fillna(df['YearsExperience'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

/tmp/ipykernel_787/3400544982.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['YearsExperience'].fillna(df['YearsExperience'].mean(), inplace=True)

In [14]:
features = df.drop('Salary', axis=1)
label = df['Salary']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(features, label, random_state=22, test_size=.2)

In [16]:
X_train.shape, X_test.shape

((24, 1), (7, 1))

In [17]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [18]:
model.predict(X_test)

array([117096.59828135, 103791.13511414, 123749.32986496,  62924.35538626,
        44866.9410879 ,  74329.03810102, 111394.25692398])

In [19]:
model.score(X_test, y_test)

0.9610566621920091

In [21]:
for rs in range(1, 101):
  X_train, X_test, y_train, y_test = train_test_split(features, label, random_state=rs, test_size=.2)
  model = LinearRegression()
  model.fit(X_train, y_train)
  print(model.score(X_test, y_test))

0.8836335910700482
0.9632458373976368
0.9330328424005482
0.8778969959795861
0.9419491184861944
0.9500598032470081
0.9665400881840488
0.9800952663501694
0.9443612644813822
0.9631154363758654
0.8426309764202654
0.9400647112579232
0.8938503020871875
0.9809416912561933
0.9217377707130867
0.8950791401302114
0.9584800549551892
0.9459036133612718
0.9687470463710981
0.9552090372223786
0.8987750109519186
0.9610566621920091
0.954679113025843
0.9537858633493538
0.9644701336456752
0.9700331153353082
0.963139013635566
0.9405835485947674
0.9774535610627699
0.9618002775009766
0.9510565286781071
0.9630860084438663
0.9305172054581534
0.8983359231013763
0.9732647995552474
0.9579132557892623
0.9769826969104595
0.9877526394814892
0.9404325790780568
0.8869010571065518
0.9557004541668429
0.9306197880495323
0.8693256636850295
0.9499511971181399
0.9247284234777186
0.9546350241964323
0.9734364725203282
0.96883441078593
0.9470018695922431
0.928769984809352
0.9603860232866948
0.9286082736976081
0.9510081433309252
0.9507719618512482
0.8847879760828339
0.9096384339618597
0.9416373562495602
0.8902602865545165
0.9739423207593948
0.9419035903480564
0.9552667371087223
0.9720991593848285
0.9370586199819066
0.9820677901713073
0.9056534491175423
0.8097426671954961
0.9618464840790083
0.9656979029364933
0.8900172849848216
0.9280280100426498
0.9544850274005822
0.9535346608287141
0.8911719232509147
0.9494929848527124
0.9659470257273842
0.8471771748737031
0.9776219128833863
0.9833196207557635
0.9351786198352067
0.9365580016137275
0.919547082385562
0.9559253645014704
0.8973238766426772
0.7736730269139653
0.961066802306572
0.9833774444780498
0.9615573282352158
0.969211419163498
0.9633930160237989
0.9676473134410937
0.9273135090978196
0.971112640159056
0.9727043884400615
0.9198194144626415
0.952526157806034
0.9495934834069313
0.9253303118223749
0.29706144489948105
0.944955607641494
0.9519429262542752